// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://movyoqalilebfrfopwnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vdnlvcWFsaWxlYmZyZm9wd253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDgzMDUsImV4cCI6MjA2NzgyNDMwNX0.KQ7hD_FK34nykE_A_naLBpa44_F9v9WBeoko11MjXdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});